const choreList = [
    "Laundry",
    "Sweep Floors",
    "Wipe Surfaces",
    "Dishes",
    "Put Laundry Away",
    "Mop Laundry Room",
    "Sweep Laundry Room",
    "Clean Kruig",
    "Clean Nightstands",
    "Vacuum",
    "Put Shoes Away",
    "Dust",
    "Sweep Bathroom",
    "Clean Toilet",
    "Clean Bathroom Counter",
    "Clean out fridge",
    "Put Dishes Away",
    "Mop Main Floor",
    "Clean Tub",
    "Wash Sheets",
    "Clean Closet",
    "Make Bed",
  ];

  export default choreList;